### ISSUE TITLE
update breaks the installation

### ISSUE THREAD

**Issue by asaage** [codefog/contao-haste#127]
```
Loading composer repositories with package information
Updating dependencies
Package operations: 0 installs, 15 updates, 0 removals
  - Updating contao-components/installer (1.2.6 => 1.2.7): Downloading (100%)
  - Updating twig/twig (v2.4.6 => v2.4.8): Downloading (100%)
  - Updating symfony/symfony (v3.4.6 => v3.4.7): Downloading (100%)
  - Updating nelmio/security-bundle (2.5.0 => 2.5.1): Downloading (100%)
  - Updating symfony/swiftmailer-bundle (v3.2.0 => v3.2.1): Downloading (100%)
  - Updating doctrine/doctrine-cache-bundle (1.3.2 => 1.3.3): Downloading (100%)
  - Updating league/uri-parser (1.3.0 => 1.4.0): Downloading (100%)
  - Updating league/uri-schemes (1.1.1 => 1.2.0): Downloading (100%)
  - Updating league/uri-components (1.7.1 => 1.8.0): Downloading (100%)
  - Updating league/uri-manipulations (1.4.0 => 1.5.0): Downloading (100%)
  - Updating guzzlehttp/guzzle (6.3.0 => 6.3.2): Downloading (100%)
  - Updating friendsofsymfony/http-cache (2.1.2 => 2.2.1): Downloading (100%)
  - Updating friendsofsymfony/http-cache-bundle (2.1.2 => 2.2.0): Downloading (100%)
  - Updating composer/ca-bundle (1.1.0 => 1.1.1): Downloading (100%)
Writing lock file
Generating optimized autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
> Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication

In ContaoModuleBundle.php line 36:
                                                                   
  The module folder "system/modules/contao-haste" does not exist.  
                                                                   

Script Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication handling the post-update-cmd event terminated with an exception
--------------------------------------------------------
Exception occured: An error occurred while executing the "contao:install-web-dir" command: 
In ContaoModuleBundle.php line 36:
                                                                   
  The module folder "system/modules/contao-haste" does not exist.  
                                                                   


#0 phar:///var/www/vhosts/xyz/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Composer/AbstractComposerCommandTask.php(166): Tenside\Core\Task\Composer\AbstractComposerCommandTask->executeCommand(Object(Composer\Command\UpdateCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Tenside\Core\Task\TaskOutput))
#1 phar:///var/www/vhosts/xyz/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Task.php(173): Tenside\Core\Task\Composer\AbstractComposerCommandTask->doPerform()
#2 phar:///var/www/vhosts/xyz/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Runner.php(89): Tenside\Core\Task\Task->perform('/var/www/vhosts...')
#3 phar:///var/www/vhosts/xyz/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(82): Tenside\Core\Task\Runner->run('/var/www/vhosts...')
#4 phar:///var/www/vhosts/xyz/web/contao-manager.phar.php/vendor/symfony/console/Command/Command.php(252): Tenside\CoreBundle\Command\RunTaskCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 phar:///var/www/vhosts/xyz/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(61): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 phar:///var/www/vhosts/xyz/web/contao-manager.phar.php/vendor/symfony/console/Application.php(964): Tenside\CoreBundle\Command\RunTaskCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 phar:///var/www/vhosts/xyz/web/contao-manager.phar.php/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Tenside\CoreBundle\Command\RunTaskCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 phar:///var/www/vhosts/xyz/web/contao-manager.phar.php/api/ApiApplication.php(71): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar:///var/www/vhosts/xyz/web/contao-manager.phar.php/vendor/symfony/console/Application.php(148): Contao\ManagerApi\ApiApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 phar:///var/www/vhosts/xyz/web/contao-manager.phar.php/api/console(83): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/vhosts/xyz/web/contao-manager.phar.php(55): require('phar:///var/www...')
#12 {main}
Chained exception: An error occurred while executing the "contao:install-web-dir" command: 
In ContaoModuleBundle.php line 36:
                                                                   
  The module folder "system/modules/contao-haste" does not exist.  
                                                                   


#0 /var/www/vhosts/xyz/vendor/contao/manager-bundle/src/Composer/ScriptHandler.php(31): Contao\ManagerBundle\Composer\ScriptHandler::executeCommand('contao:install-...', Object(Composer\Script\Event))
#1 phar:///var/www/vhosts/xyz/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/EventDispatcher/EventDispatcher.php(282): Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication(Object(Composer\Script\Event))
#2 phar:///var/www/vhosts/xyz/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/EventDispatcher/EventDispatcher.php(205): Composer\EventDispatcher\EventDispatcher->executeEventPhpScript('Contao\\ManagerB...', 'initializeAppli...', Object(Composer\Script\Event))
#3 phar:///var/www/vhosts/xyz/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/EventDispatcher/EventDispatcher.php(96): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Script\Event))
#4 phar:///var/www/vhosts/xyz/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/Installer.php(322): Composer\EventDispatcher\EventDispatcher->dispatchScript('post-update-cmd', false)
#5 phar:///var/www/vhosts/xyz/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/Command/UpdateCommand.php(161): Composer\Installer->run()
#6 phar:///var/www/vhosts/xyz/web/contao-manager.phar.php/vendor/symfony/console/Command/Command.php(252): Composer\Command\UpdateCommand->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Tenside\Core\Task\TaskOutput))
#7 phar:///var/www/vhosts/xyz/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Composer/AbstractComposerCommandTask.php(147): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Tenside\Core\Task\TaskOutput))
#8 phar:///var/www/vhosts/xyz/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Composer/AbstractComposerCommandTask.php(166): Tenside\Core\Task\Composer\AbstractComposerCommandTask->executeCommand(Object(Composer\Command\UpdateCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Tenside\Core\Task\TaskOutput))
#9 phar:///var/www/vhosts/xyz/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Task.php(173): Tenside\Core\Task\Composer\AbstractComposerCommandTask->doPerform()
#10 phar:///var/www/vhosts/xyz/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Runner.php(89): Tenside\Core\Task\Task->perform('/var/www/vhosts...')
#11 phar:///var/www/vhosts/xyz/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(82): Tenside\Core\Task\Runner->run('/var/www/vhosts...')
#12 phar:///var/www/vhosts/xyz/web/contao-manager.phar.php/vendor/symfony/console/Command/Command.php(252): Tenside\CoreBundle\Command\RunTaskCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 phar:///var/www/vhosts/xyz/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(61): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 phar:///var/www/vhosts/xyz/web/contao-manager.phar.php/vendor/symfony/console/Application.php(964): Tenside\CoreBundle\Command\RunTaskCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 phar:///var/www/vhosts/xyz/web/contao-manager.phar.php/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Tenside\CoreBundle\Command\RunTaskCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 phar:///var/www/vhosts/xyz/web/contao-manager.phar.php/api/ApiApplication.php(71): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 phar:///var/www/vhosts/xyz/web/contao-manager.phar.php/vendor/symfony/console/Application.php(148): Contao\ManagerApi\ApiApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 phar:///var/www/vhosts/xyz/web/contao-manager.phar.php/api/console(83): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/vhosts/xyz/web/contao-manager.phar.php(55): require('phar:///var/www...')
#20 {main}
--------------------------------------------------------


Process terminated with exit code 1
Reason: General error
```

not shure what is going on here...
The module folder "system/modules/contao-haste" does indeed **exist**. 
But i went through this update-procedure twice this morning (with the contao manager 1.0.0-beta17) and both times it failed with the same reason.

**Comment by aschempp** [comment]
This is a Contao Core issue (see https://github.com/contao/manager-bundle/issues/61)

**Comment by asaage** [comment]
thank you
